export { createAstraScene, DEFAULT_CONFIG } from './scene.js'
export { createAstraField, generateStarField, DEFAULT_FIELD_OPTIONS } from './field.js'
export { detectWebGL, prefersReducedMotion, renderStaticFallback } from './fallback.js'
export { AstraLensFlare, DEFAULT_FLARE } from './lensflare.js'
export { AstraBloomEffect } from './bloom.js'
export { PALETTES } from './palette.js'
export { GALAXY_PATHS, GALAXY_LAYERS, createGalaxyLayers } from './paths.js'
export { rasterize } from './rasterize.js'
export { extractContours } from './contours.js'
